import 'package:flutter/material.dart';

/// Color schemes generated from Material Theme Builder
/// Source: minha-saude-material.json
class AppColorSchemes {
  /// Light theme color scheme
  static const light = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xff006879),
    surfaceTint: Color(0xFF006879),
    onPrimary: Color(0xFFFFFFFF),
    primaryContainer: Color(0xFFA9EDFF),
    onPrimaryContainer: Color(0xFF004E5C),
    secondary: Color(0xFF4B6268),
    onSecondary: Color(0xFFFFFFFF),
    secondaryContainer: Color(0xFFCEE7EE),
    onSecondaryContainer: Color(0xFF334A50),
    tertiary: Color(0xFF565D7E),
    onTertiary: Color(0xFFFFFFFF),
    tertiaryContainer: Color(0xFFDDE1FF),
    onTertiaryContainer: Color(0xFF3E4565),
    error: Color(0xFFBA1A1A),
    onError: Color(0xFFFFFFFF),
    errorContainer: Color(0xFFFFDAD6),
    onErrorContainer: Color(0xFF93000A),
    surface: Color(0xFFF5FAFC),
    onSurface: Color(0xFF171C1E),
    onSurfaceVariant: Color(0xFF3F484B),
    outline: Color(0xFF70797B),
    outlineVariant: Color(0xFFBFC8CB),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFF2B3133),
    onInverseSurface: Color(0xFFECF2F4),
    inversePrimary: Color(0xFF84D2E6),
    primaryFixed: Color(0xFFA9EDFF),
    onPrimaryFixed: Color(0xFF001F26),
    primaryFixedDim: Color(0xFF84D2E6),
    onPrimaryFixedVariant: Color(0xFF004E5C),
    secondaryFixed: Color(0xFFCEE7EE),
    onSecondaryFixed: Color(0xFF061F24),
    secondaryFixedDim: Color(0xFFB2CBD2),
    onSecondaryFixedVariant: Color(0xFF334A50),
    tertiaryFixed: Color(0xFFDDE1FF),
    onTertiaryFixed: Color(0xFF121A37),
    tertiaryFixedDim: Color(0xFFBEC5EB),
    onTertiaryFixedVariant: Color(0xFF3E4565),
    surfaceDim: Color(0xFFD5DBDD),
    surfaceBright: Color(0xFFF5FAFC),
    surfaceContainerLowest: Color(0xFFFFFFFF),
    surfaceContainerLow: Color(0xFFEFF4F6),
    surfaceContainer: Color(0xFFE9EFF1),
    surfaceContainerHigh: Color(0xFFE4E9EB),
    surfaceContainerHighest: Color(0xFFDEE3E5),
  );

  /// Dark theme color scheme
  static const dark = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF84D2E6),
    surfaceTint: Color(0xFF84D2E6),
    onPrimary: Color(0xFF003640),
    primaryContainer: Color(0xFF004E5C),
    onPrimaryContainer: Color(0xFFA9EDFF),
    secondary: Color(0xFFB2CBD2),
    onSecondary: Color(0xFF1D343A),
    secondaryContainer: Color(0xFF334A50),
    onSecondaryContainer: Color(0xFFCEE7EE),
    tertiary: Color(0xFFBEC5EB),
    onTertiary: Color(0xFF282F4D),
    tertiaryContainer: Color(0xFF3E4565),
    onTertiaryContainer: Color(0xFFDDE1FF),
    error: Color(0xFFFFB4AB),
    onError: Color(0xFF690005),
    errorContainer: Color(0xFF93000A),
    onErrorContainer: Color(0xFFFFDAD6),
    surface: Color(0xFF0F1416),
    onSurface: Color(0xFFDEE3E5),
    onSurfaceVariant: Color(0xFFBFC8CB),
    outline: Color(0xFF899295),
    outlineVariant: Color(0xFF3F484B),
    shadow: Color(0xFF000000),
    scrim: Color(0xFF000000),
    inverseSurface: Color(0xFFDEE3E5),
    onInverseSurface: Color(0xFF2B3133),
    inversePrimary: Color(0xFF006879),
    primaryFixed: Color(0xFFA9EDFF),
    onPrimaryFixed: Color(0xFF001F26),
    primaryFixedDim: Color(0xFF84D2E6),
    onPrimaryFixedVariant: Color(0xFF004E5C),
    secondaryFixed: Color(0xFFCEE7EE),
    onSecondaryFixed: Color(0xFF061F24),
    secondaryFixedDim: Color(0xFFB2CBD2),
    onSecondaryFixedVariant: Color(0xFF334A50),
    tertiaryFixed: Color(0xFFDDE1FF),
    onTertiaryFixed: Color(0xFF121A37),
    tertiaryFixedDim: Color(0xFFBEC5EB),
    onTertiaryFixedVariant: Color(0xFF3E4565),
    surfaceDim: Color(0xFF0F1416),
    surfaceBright: Color(0xFF343A3C),
    surfaceContainerLowest: Color(0xFF090F11),
    surfaceContainerLow: Color(0xFF171C1E),
    surfaceContainer: Color(0xFF1B2122),
    surfaceContainerHigh: Color(0xFF252B2D),
    surfaceContainerHighest: Color(0xFF303637),
  );
}
